version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - ./data:/app/data
    environment:
      - DATABASE_URL=mysql://bolioforo:password@db:3306/bolioforo
    depends_on:
      - db
  db:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=bolioforo
      - MYSQL_USER=bolioforo
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"

volumes:
  mariadb_data: