version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - ./data:/app/data
    environment:
      - NODE_ENV=development